Second deliver
wizelineacademy/react-bootcamp-2020 pull request #38
Opened 2020-12-14 05:08 UTC by livier92

2020-12-15 21:36 UTC, wdonet requested changes
Just a few comments, it seems you made it 👌🏽 , however, work on CSS styling to make the videos at the list to look at the right size instead of being stretched, assure all buttons are visible using the current viewport

2020-12-15 21:36 UTC, wdonet commented on src/components/App/App.component.js
> +              <Protected path="/favorites" component={FavoritesPage} />
Good you defined a protected route however I could not see it working or even a way to mark a video as favourite :/

2020-12-15 21:36 UTC, wdonet commented on src/components/VideoList/VideoList.component.js
> +  console.log(props);
do not leave"console.logs" at deliverables

2020-12-15 21:36 UTC, wdonet commented on src/pages/VideoPlayer/VideoPlayer.page.js
> +    <MainPane>
oh got it, thanks to this component I was able to find the button to add a fav video, however, this seems to be hidden at the bottom of the page, probably you can fix it by playing with styles

2020-12-15 21:36 UTC, wdonet commented on src/state/videoReducer.js
> +      console.log('add reducer');
use logs only at development time

2020-12-17 01:47 UTC, jparciga reviewed
The app is working, good job! It would've been great that you have implemented tests for your components, hooks and utils. You forgot to implement related videos list on the video page. Some styles are broken on mobile.

2020-12-17 01:47 UTC, jparciga commented on src/components/NavBar/NavBar.component.js
> +            <LogoutSpan className="nav-link" onClick={handleLogout} href="/">
I think that the `href` attribute is not necessary here

2020-12-17 01:47 UTC, jparciga commented on src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu',
Please make sure to embed this font files from Google Fonts or from file declared on a `@font-face {}` statement

2020-12-17 01:47 UTC, jparciga commented on src/utils/hooks/useYoutubeAPI.js
> +          apiKey: process.env.REACT_APP_API_KEY,
👌🏻

2021-01-03 21:33 UTC, closed without merging